# Compiler and flags
CXX = g++
CXXFLAGS = -std=c++11 -Wall -static-libgcc -static-libstdc++
LDFLAGS = -L"C:/SFML-2.4.0/lib"
INCLUDES = -I"C:/SFML-2.4.0/include"

# SFML libraries (dynamic linking)
LIBS = -lsfml-graphics -lsfml-window -lsfml-system -lsfml-audio

# Source files
SOURCES = main.cpp Game.cpp Ghost.cpp Maze.cpp Pacman.cpp
OBJECTS = $(SOURCES:.cpp=.o)
EXECUTABLE = pacman.exe

# Rules
all: $(EXECUTABLE)

$(EXECUTABLE): $(OBJECTS)
	$(CXX) $(OBJECTS) -o $@ $(LDFLAGS) $(LIBS)

.cpp.o:
	$(CXX) $(CXXFLAGS) $(INCLUDES) -c $< -o $@

clean:
	del *.o $(EXECUTABLE)